openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /dsl/check:
    security:
      - basicAuth: []
    post:
      description: "Hello World!"
      responses:
        "401":
          description: "Unauthorized"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Unauthorized"
        "200":
          description: "Returns OK for both syntactically correct and incorrect DSLs"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: "syntax error...."


components:
  schemas: {}
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
